// SPDX-License-Identifier: Apache-2.0
pragma solidity 0.8.24;

/// @title IHalo2Verifier
/// @notice Stable interface for the auto-generated Halo2-KZG verifier deployed in Phase 2.
/// @dev The Solidity verifier is auto-generated by PSE snark-verifier from the Rust circuit.
///      A version of this verifier is deployed per circuit revision; MerkleStateRegistry
///      holds a verifier address per credDef so different credDefs can use different
///      circuit versions during a migration.
interface IHalo2Verifier {
    /// @notice Verify a Halo2-KZG proof.
    /// @param proof The encoded proof bytes.
    /// @param publicSignals The public input values, ordered exactly as the circuit expects.
    /// @return ok True if the proof is valid.
    function verify(bytes calldata proof, bytes32[] calldata publicSignals) external view returns (bool ok);

    /// @notice Identifier of the circuit version this verifier corresponds to.
    /// @dev Used by indexers and SDKs to align provers with verifiers.
    function circuitVersion() external view returns (bytes32);
}
